### ISSUE TITLE
Problem with node-gyp rebuild when installing node modules in the process folder

### ISSUE THREAD

**Issue by UncleGus** [Kazetsukai/onetech#34]
```
david@david-ubuntu:~/MyLife/onetech/process(master)$ npm i

> canvas@1.6.9 install /home/david/MyLife/onetech/process/node_modules/canvas
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/david/.nvm/versions/node/v9.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/home/david/.nvm/versions/node/v9.9.0/bin/node" "/home/david/.nvm/versions/node/v9.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/david/MyLife/onetech/process/node_modules/canvas
gyp ERR! node -v v9.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN onetech-process@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2018-03-27T00_43_44_761Z-debug.log
david@david-ubuntu:~/MyLife/onetech/process(master)$
```

**Comment by ryanb** [comment]
You will need to install the dependencies for canvas. Check out [the instructions here](https://github.com/Automattic/node-canvas/blob/v1.x/Readme.md)

**Comment by UncleGus** [comment]
Thanks, that resolved it.
