### ISSUE TITLE
Started getting an undefined object when processing categories:

### ISSUE THREAD

**Issue by UncleGus** [Kazetsukai/onetech#72]
```
/home/david/MyLife/onetech/process/src/Category.js:18
      object.categories.push(this);
             ^

TypeError: Cannot read property 'categories' of undefined
    at Category.addToObjects (/home/david/MyLife/onetech/process/src/Category.js:18:14)
    at eachFileInDir (/home/david/MyLife/onetech/process/src/GameData.js:49:16)
    at GameData.eachFileInDir (/home/david/MyLife/onetech/process/src/GameData.js:145:7)
    at GameData.importCategories (/home/david/MyLife/onetech/process/src/GameData.js:47:10)
    at Object.<anonymous> (/home/david/MyLife/onetech/process/process.js:17:10)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

**Comment by ryanb** [comment]
@UncleGus I think there is a category file which references an object ID which doesn't exist. I'll make this error more clear to specify which one is missing.
